sm8450-common: oplus-fwk: Use correct class name for OplusNetworkUtil
* Fix typo causing camera watermark location crash - Thanks to Mrick343

msg: java.lang.ClassNotFoundException: com.oplus.util.OplusNetworkUtil
stacktrace: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/oplus/util/OplusNetworkUtil;
	at ah.h1.f(CameraSubSettingFragment.java:24)
	at ah.a1.f(R8$$SyntheticClass:5)
	at androidx.preference.Preference.a(Preference.java:5)
	at androidx.preference.TwoStatePreference.y(TwoStatePreference.java:9)
	at androidx.preference.Preference.H(Preference.java:13)
	at androidx.preference.CheckBoxPreference.H(CheckBoxPreference.java:1)
	at androidx.preference.Preference$a.onClick(Preference.java:3)
	at android.view.View.performClick(View.java:7730)
	at android.view.View.performClickInternal(View.java:7707)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30491)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8496)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ClassNotFoundException: com.oplus.util.OplusNetworkUtil

Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>